# -*- coding: utf-8 -*-
"""TP05-19921122.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BXsZis_yCBCB47hfuaIBpf6xR2OUI5t4

Identitas Diri
"""

# Nama      : Salma Sari Juliani
# NIM       : 19921122
# Deskripsi : TP Pengenalan Komputasi Modul 5

"""Code"""

# import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

data_frame = pd.read_csv('data_tp.csv')

# 1. membaca 5 entri pertama data
data_frame.head()

# 2. scatter plot data 
plt.scatter(data_frame['tinggi_anak'], data_frame['berat_anak'], color='violet')

plt.xlabel('Tinggi Anak')
plt.ylabel('Berat Anak')
plt.title('Scatter Plot Tinggi Anak vs Berat Anak')
plt.show()

# 3. box plot data

# box plot tinggi anak
plt.boxplot(data_frame['tinggi_anak'])
plt.title('Box Plot Tinggi Anak')
plt.show()

# box plot berat anak
plt.boxplot(data_frame['berat_anak'])
plt.title('Box Plot Berat Anak')
plt.show()

# 4. model regresi linear
x = data_frame['tinggi_anak'].values.reshape(-1,1)
y = data_frame['berat_anak'].values.reshape(-1,1)

hahaha = LinearRegression().fit(x,y)

print('a:', hahaha.intercept_)
print('b:', hahaha.coef_)
print('')
print('Maka, didapatkan persamaan :')
print('y = 37.53029119 + 0.2206901x')

# 5. visualisasi model regresi linear dan scatter plot data asli
regresi = hahaha.predict(x)

plt.scatter(x,y, color='pink')
plt.plot(x, regresi, color='lightgreen')
plt.xlabel('Tinggi Badan')
plt.ylabel('Berat Badan')
plt.title('Plot Tinggi Badan vs Berat Badan')
plt.show()

# 6. nilai R-squared 
print('R-squared: ', hahaha.score(x,y))

# karena nilai R-squared mendekati 1, maka model regresi yang saya gunakan 
# sudah baik dan tepat

# 7. prediksi berat anak untuk tinggi anak sebesar 150 cm dan 155 cm
y_prediksi = hahaha.predict([[150], [155]])
print(y_prediksi)

# cara manual
a = 37.53029119 + 0.2206901*150
s = 37.53029119 + 0.2206901*155

print('saat x = 150, nilai y adalah:', a)
print('saat x = 155, nilai y adalah:', s)